export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGGED_OUT = 'LOGGED_OUT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const AUTH_FAIL = 'AUTH_FAIL'
export const USER_LOADED = 'USER_LOADED'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const ITEMS_LOADED = 'ITEMS_LOADED'
export const ITEM_LOADED = 'ITEM_LOADED'

export const LOAD_ITEMS_FAIL = 'LOAD_ITEMS_FAIL'

export const ADDED_CART = 'ADDED_CART'
export const ADD_CART_FAIL = 'ADD_CART_FAIL'
export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS'
export const LOAD_CART_FAIL = 'LOAD_CART_FAIL'
export const REMOVED_ITEM = 'REMOVED_ITEM'
